#!/usr/bin/with-contenv bash

if [ -f /usr/bin/apt ]; then ## Ubuntu
    if ! dpkg -l envsubst > /dev/null; then
        echo "**** Adding envsubst deps to package install list ****"
        echo "envsubst" >> /mod-repo-packages-to-install.list
    else
        echo "**** envsubst deps already installed, skipping ****"
    fi
elif [ -f /sbin/apk ]; then ## Alpine
    if ! apk info 2>&1 | grep -q "envsubst"; then
        echo "**** Adding envsubst deps to package install list ****"
        echo "envsubst" >> /mod-repo-packages-to-install.list
    else
        echo "**** envsubst deps already installed, skipping ****"
    fi
else
    echo "**** Unsupported OS ****"
    exit 1
fi
