#!/usr/bin/with-contenv bash

if [ -f /usr/bin/apt ]; then ## Ubuntu
  echo "tini" >> /mod-repo-packages-to-install.list
elif [ -f /sbin/apk ]; then ## Alpine
  echo "tini-static" >> /mod-repo-packages-to-install.list
else
  echo "**** Unsupported OS ****"
  exit 1
fi
