#!/usr/bin/with-contenv bash

ENVSUBST_TARGET="${ENVSUBST_TARGET:-/config/config.xml}"
ENVSUBST_SOURCE="${ENVSUBST_SOURCE:-${ENVSUBST_TARGET}.tmpl}"

if [ -f "${ENVSUBST_TARGET}" ]; then
    if [ -f "${ENVSUBST_TARGET}.bak" ]; then
        mv "${ENVSUBST_TARGET}.bak" "${ENVSUBST_TARGET}_2.bak"
    fi
    mv "${ENVSUBST_TARGET}" "${ENVSUBST_TARGET}.bak"
fi

if [ ! -f "${ENVSUBST_SOURCE}" ]; then
    echo "**** ${ENVSUBST_SOURCE} not found, skipping ****"
    exit 0
fi

envsubst < "${ENVSUBST_SOURCE}" > "${ENVSUBST_TARGET}"
