#!/usr/bin/with-contenv bash

ENVSUBST_SEPARATOR="${ENVSUBST_SEPARATOR:-|}"
ENVSUBST_TEMPLATES="${ENVSUBST_TEMPLATES:-/config/config.xml.tmpl}"

IFS="${ENVSUBST_SEPARATOR}" read -r -a TEMPLATE_LIST <<<"${ENVSUBST_TEMPLATES}"

function _backup {
  target="${1%.*}"
  if [ -f "${target}" ]; then
    echo "**** Backing up ${target} ****"
    if [ -f "${target}.bak" ]; then
        mv "${target}.bak" "${target}_2.bak"
    fi
    mv "${target}" "${target}.bak"
  fi
}

function _process {
  source="${1}"
  target="${source%.*}"
  echo "**** Processing ${source} ****"
  if [ -f "${source}" ]; then
    echo "**** Running envsubst for ${source} ****"
    envsubst < "${source}" > "${target}"
  else
    echo "**** ${source} not found, skipping ****"
  fi
}

for src in "${TEMPLATE_LIST[@]}"; do
  _backup "${src}"
  _process "${src}"
done
