name: Build and Release Charts Pages and OCI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - ./**/Dockerfile

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      files: ${{ steps.prepare-files.outputs.files }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Output changed files
        id: prepare-files
        run: |
          changed=$(git diff --name-only HEAD HEAD~1 | grep Dockerfile | wc -l)
          
          if [[ $changed -eq 0 ]]; then
            echo "No Dockerfiles changed"
            echo "files=[]" >> $GITHUB_OUTPUT
            exit 0
          fi

          files=$(echo "${changed[@]%/Dockerfile}" | jq -R -s -c 'split("\n") | map(select(length>0))')

          echo "files=${files}" >> $GITHUB_OUTPUT

  release:
    name: Release Helm charts
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
      pages: write

    needs: ["prepare"]

    strategy:
      fail-fast: false
      matrix:
        file: ["${{ fromJSON(needs.prepare.outputs.files || '[]') }}"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to OCI registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "${{ matrix.file }}"
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.sha }}:latest
